### PR TITLE
fixes

### PR DESCRIPTION
**Pull request by maltegrosse**

### CODE REVIEW

**Comment by smuroff** [comment]
@maltegrosse hi, thank you for your work on modemmanager bindings for golang. What do you think about to merge this PR? Tell me if you need help ;)

**Comment by maltegrosse** [comment]
@marvelou-s Hi, thanks for reminding me. Currently focusing on some other projects and run out of time. The go build fails (pipeline) somehow on Github. If you can figure this out - a PR is more than welcomed :)

**Comment by smuroff** [comment]
Build failed because of missing SetProperty method on BusObject. which appeared since v5.0.2. No need to change imports. 
BTW, I'm gonna create new PR to clean up logs and typos in json tags.

**Comment by maltegrosse** [comment]
see #3

**Pull request closed without merging**
